name: candies
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.1.4
  logger: ^2.0.2+1
  flutter_bloc: ^8.1.5
  gap: ^3.0.1
  get_it: ^7.7.0
  equatable: ^2.0.5
  shared_preferences: ^2.3.1
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  share_plus: ^10.1.3
  uuid: ^4.5.1
  percent_indicator: ^4.2.4
  flutter_svg: ^2.0.17


dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/json/

  fonts:
    - family: Florida
      fonts:
        - asset: assets\fonts\Florida.otf

    - family: Hugmate
      fonts:
        - asset: assets\fonts\Hugmate.ttf

    - family: Poetsen
      fonts:
        - asset: assets\fonts\Poetsen.ttf

